### DISCUSSION TITLE
Limited Area Modelling

### DISCUSSION THREAD

**Discussion by slicedBread789** [ecmwf/anemoi-core#192] [General]
Hi everyone, I'm new to AnemoI and wonder if people have advice on how to use AnemoI for limited area modelling. In particular what variables to use, choice of loss functions and spatial resolution.  

I've created a yaml file for training and put the following. I couldn't get the CombinedLoss to work so am using MAELoss only (hence the other lines are commented out). I also couldn't get AnemoI to use a previously generated Graph so a few minutes are wasted recalculating every time I start training.

Any suggestions are much appreciated.
```
graph:
        #overwrite: False
        nodes:
                # Data nodes
                data:
                        node_builder:
                                _target_: anemoi.graphs.nodes.ZarrDatasetNodes
                                dataset: ${dataloader.training.dataset}
                        attributes: ${graph.attributes.nodes}
                # Hidden nodes
                hidden:
                        node_builder:
                                _target_: anemoi.graphs.nodes.LimitedAreaTriNodes # options: ZarrDatasetNodes, NPZFileNodes, TriNodes
                                resolution: 9 # grid resolution for npz (o32, o48, ...)
                                reference_node_name: ${graph.data}
                                mask_attr_name: cutout_mask

model:
  output_mask: cutout_mask # it must be a node attribute of the output nodes
  num_channels: 256

training:
        rollout:
                start: 1
                epoch_increment: 1
                max: 3
        training_loss:
                #_target_: anemoi.training.losses.combined.CombinedLoss
                _target_: anemoi.training.losses.mae.WeightedMAELoss
                #losses:
                #        - _target_: anemoi.training.losses.mse.WeightedMSELoss
                #        - _target_: anemoi.training.losses.mae.WeightedMAELoss
                #loss_weights: [0.5,0.5]
                scalars: ['variable', 'loss_weights_mask']                
        variable_loss_scaling:
                default: 1
                pl:
                        q: 1   #1
                        t: 1   #1
                        u: 1 #0.5
                        v: 1 #0.33
                        w: 0.001
                        z: 2  #1
                sfc:
                        sp: 1
                        2t: 10
                        10u: 2
                        10v: 1
                        2d: 1
                        tp: 0.25
                        cp: 0.00025

```
