### ISSUE TITLE
Date-agnostic way to define training/validation split of dataset

### ISSUE THREAD

**Issue by cathalobrien** [ecmwf/anemoi-core#15]
### Is your feature request related to a problem? Please describe.

Currently I define my training/validation split like so
```yaml
  training:
    start: null
    end: 2020
  validation:
    start: 2021
    end: 2021
```
This breaks when i change to a different dataset which covers a different date range. Then I am forced to use my brain to remember the syntax and think up a different set of dates that fall within the new dataset. When all I really want is an 80% training 20% validation split.

### Describe the solution you'd like

It would be nice if there was a way to select fractions of the dataset, without having to mention dates. This would make the same config portable to datasets covering different date ranges. An example of an 80% training 20% validation split is below, where I give fractions as floats (and ideally Anemoi will work out the date ranges itself).
```yaml
  training:
    start: 0.0
    end: 0.8
  validation:
    start: 0.9
    end: 1.0
```

### Organisation

ECMWF

**Comment by floriankrb** [comment]
Implemented here: https://github.com/ecmwf/anemoi-datasets/pull/167

Note that in your initial example, one date is duplicated in training and validation because the convention is to include the limits in the interval.

This should work:

```
  training:
    start: 0%
    end: 80%
  validation:
    start: 80.00000000001%
    end: 100%
```
