### ISSUE TITLE
Allow noncontinous time ranges in datasets for training and validation

### ISSUE THREAD

**Issue by HCookie** [ecmwf/anemoi-core#17]
### Is your feature request related to a problem? Please describe.

Currently training, validation and test datasets are continuous time ranges. While this makes sense, it may be interesting to explore other ways of organising the time slices.

### Describe the solution you'd like

Add a way to provide ranges of time to the dataloader, allowing the following config.
```yaml
training:
  dataset: ${dataloader.dataset}
  ranges: 
    - [1970, 1980]
    - [1990, 2020]
  frequency: ${data.frequency}
  drop:  []


validation:
  dataset: ${dataloader.dataset}
  ranges: 
    - [1981, 1989]
    - [2021, 2021]
  frequency: ${data.frequency}
  drop:  []
```

### Organisation

ECMWF
