### ISSUE TITLE
Mlflow logging LR duplicate key issue with PostgreSQL DB

### ISSUE THREAD

**Issue by anaprietonem** [ecmwf/anemoi-core#190]
### What happened?

We are aware that when running anemoi-training using an mlflow server to log your results. If using online logging, some people are hitting the following error:
```
`mlflow.exceptions.RestException: BAD_REQUEST: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "metric_pk"
DETAIL:  Key (key, "timestamp", step, run_uuid, value, is_nan)=(lr-AdamW, 1741862947817, 60899, 843c1331fefa436bab56485cfc5bc16e, 0.000322870392593084, f) already exists.`

```

### What are the steps to reproduce the bug?

`anemoi-training train` with mlflow:enabled and offline:False

### Version

Latest

### Platform (OS and architecture)

ATOS & LUMI

### Relevant log output

```shell

```

**Comment by anaprietonem** [comment]
Errors reported by colleagues at DMI (@dietervdb-meteo). The config used:
```
training:
  run_id:  ba67b02f88ff488c9365735c571a88e5
  max_epochs: null # set max_epochs or max_steps. Training stops at the first limit reached.
  max_steps: 150000 #NOTE: increase to 300,000 for high-accuracy full-scale run on LUMI

  lr:
    rate: 2.5e-4  #4 * 0.625e-4
    min: 1.2e-6 #4 * 3e-7
    iterations: ${training.max_steps}
    warmup_t: 1000
````

[mlflow_issue (1).log](https://github.com/user-attachments/files/19244281/mlflow_issue.1.log)
