### ISSUE TITLE
Graph Create on a complete config doesn't throw errors

### ISSUE THREAD

**Issue by icedoom888** [ecmwf/anemoi-core#296]
### What happened?

Running the command: 

anemoi-graph create config.yaml

with a complete training config will not throw any error and just build an empty graph.

One of the two should happen:

- error is thrown
- anemoi-graph reads inside the graph section of the config and executes the command

### What are the steps to reproduce the bug?

Running the command: 

anemoi-graph create config.yaml

with a complete training config will not throw any error and just build an empty grap

### Version

models 0.5.1

### Platform (OS and architecture)

Linux balfrin-ln002 5.14.21-150400.24.81_12.0.87-cray_shasta_c #1 SMP Sun Dec 17 12:59:08 UTC 2023 (e30c7c1) x86_64 x86_64 x86_64 GNU/Linux

### Relevant log output

```shell

```

### Organisation

meteoswiss

**Comment by JPXKQX** [comment]
Minimal config to reproduce error:
```
nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes
      resolution: 6

  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes
      resolution: 5

edges:
- source_name: data
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 12
- source_name: hidden
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.MultiScaleEdges
    x_hops: 1
    scale_resolutions: null
- source_name: hidden
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 3
```
It works when running on a CPU or 1 GPU, but fails when running on 2 or 4 GPUs.
