### ISSUE TITLE
Decoder keyword `initialise_data_extractor_zero` cannot be used with boundings.

### ISSUE THREAD

**Issue by jakob-schloer** [ecmwf/anemoi-core#346]
### What happened?

When the `config.model.decoder.initialise_data_extractor_zero = True` the weights of the last layer are initialized to zero which leads to zeros in the diagnostic output fields after initialization (prognostic fields are residual and thus are not zero). In combination with some bounding, e.g. ReLuBounding, the gradients are zero and the fields are never learned. 

### What are the steps to reproduce the bug?

In the config set: 

```
data:
  diagnostic:
    - tp

model: 
  decoder:
    ...
    initialise_data_extractor_zero = True

  bounding: #These are applied in order
    - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
       variables:
         - tp
```

Tp will always be zero, see mlflow run: 
[uniform_decoder_initialization](https://mlflow.ecmwf.int/#/experiments/266/runs/71c69667271e4e34bd04b7601f6795e8/artifacts)
[zero_decoder_initialization](https://mlflow.ecmwf.int/#/experiments/266/runs/f3d8bad407b44b2d9e38f0a70c5aa0b9/artifacts)

### Suggestion for fix

Create a big warning that you cannot use zero-weight initialization with bounding, potentially in Pydantic. 

### Version

v0.5.1

### Platform (OS and architecture)

ATOS

### Organisation

ECMWF
