### ISSUE TITLE
DatasetMask as additional node attribute

### ISSUE THREAD

**Issue by sabrinawahl** [ecmwf/anemoi-core#350]
### Is your feature request related to a problem? Please describe.

For regional modelling we have a set of (zarr) datasets  which define the input data nodes from different sources (global and regional). The input data nodes are concatenated via the grids command: 
```
graph:
  nodes:
    data:
      node_builder:
        _target_: anemoi.graphs.nodes.ZarrDatasetNodes
        dataset:
          grids:
            - dataset_lam.zarr
            - dataset_global.zarr
 ```
For the creation of customized encoder/decoder edges for global and regional we need to create a boolean data set mask as additional node attribute for each dataset separately (similar to CutOffMask). This enables the use of different edge builders for the different datasets.
```
  edges:
    - source_name: data
      target_name: hidden
      edge_builders:
      - _target_: anemoi.graphs.edges.CutOffEdges
        cutoff_factor: 0.9
        source_mask_attr_name: lam_mask
      - _target_: anemoi.graphs.edges.KNNEdges
        num_nearest_neighbours: 6
        source_mask_attr_name: global_mask
```

### Describe the solution you'd like

Add a new class to `anemoi.graphs.nodes.attributes.masks.py` similar to [CutOutMask](https://github.com/ecmwf/anemoi-core/blob/0e8bb998176bea2d653ca40772e4e6e1578551f7/graphs/src/anemoi/graphs/nodes/attributes/masks.py#L53-L62) which returns a boolean mask for a given dataset (first, second,...).

### Organisation

DWD
