### ISSUE TITLE
SphericalAreaWeights not working as intended for high resolution stretched grid

### ISSUE THREAD

**Issue by havardhhaugen** [ecmwf/anemoi-core#362]
### What happened?

SphericalAreaWeights do not work as intended with a high resolution stretched grid setup (n320 global, 2.5km regional resolution). 

![Image](https://github.com/user-attachments/assets/2ef22212-16da-4dd8-9799-61f457b3d2de)

This can be fixed by not casting the latitude / longitude coordinates to float32 (keeping them as float64). I would guess this bug happens because SphericalVoronoi's internal precision depends on that of the input data. Correct result when not casting to float32:

![Image](https://github.com/user-attachments/assets/b8f26c03-f6b9-4150-934b-ab896c30ea6e)

### What are the steps to reproduce the bug?

Create a graph using cutout with the default stretched grid graph config and 
```yaml
  dataset:
    cutout:
      - dataset: aifs-meps-2.5km-2020-2023-6h-v7
        trim_edge: 50
      - dataset: aifs-ea-an-oper-0001-mars-n320-1979-2022-6h-v6
    min_distance_km: 0
    adjust: all
```

### Version

v0.6.0

### Platform (OS and architecture)

Leonardo

### Relevant log output

```shell

```

### Organisation

MetNorway
