### ISSUE TITLE
CombinedLoss not working/not tested

### ISSUE THREAD

**Issue by OpheliaMiralles** [ecmwf/anemoi-core#68]
### What happened?

The node_weights tensor is never passed as an argument to individual losses. The node_loss_weights resolves with hydra in a GraphNodeAttribute which does not translate anywhere into a tensor other than through the get_node_weights method from the GraphForecaster. 
It means that the node_weights tensor is provided as a kwarg to the CombinedLoss init, which does not need it, but when hydra instantiates the individual losses, there is no tensor but only a GraphNodeAttribute object.
Reminder: the CombinedLoss is not tested.

### What are the steps to reproduce the bug?

Write that in the training config (the documentation string is wrong, node_weights is not provided anywhere if you follow it). 
```

training_loss:
  _target_: anemoi.training.losses.combined.CombinedLoss
  losses:
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      node_weights: ${training.node_loss_weights_resolved}
    - _target_: anemoi.training.losses.mae.WeightedMAELoss
      node_weights: ${training.node_loss_weights_resolved}
  scalars:
    - variable
  loss_weights:
    - 1.0
    - 0.5
  ignore_nans: True

node_loss_weights:
  _target_: anemoi.training.losses.nodeweights.GraphNodeAttribute
  target_nodes: ${graph.data}
  node_attribute: area_weight
  
node_loss_weights_resolved: ${training.node_loss_weights}
```

### Version

latest develop

### Platform (OS and architecture)

Linux balfrin-ln002 5.14.21-150400.24.81_12.0.87-cray_shasta_c

### Accompanying data

MeteoSwiss

### Organisation

MeteoSwiss
