### ISSUE TITLE
Seperation of Dependencies

### ISSUE THREAD

**Issue by HCookie** [ecmwf/anemoi-core#96]
### What maintenance does this project need?

As we saw in #81, a bug/breaking change in one of our dependencies, can cripple the install of this package.

With #81, `datashader` is only needed in the plotting callbacks, this is not a critical component of `training` and ultimately should not be required dependency. 

We should seperate these into optional dependencies and catch when a part of training is trying to use an uninstalled package.

```toml
# Optional Dependencies
[optional-dependencies]
plotting = ['datashader', 'matplotlib']
...
```

What other splits of dependencies make sense?

### Organisation

ECMWF
