### ISSUE TITLE
Better config interface for NormalizedReluBounding

### ISSUE THREAD

**Issue by lzampier** [ecmwf/anemoi-core#99]
### Is your feature request related to a problem? Please describe.

Calling the NormalizedReluBounding can be slightly counterintuitive as it is right now. Here is an example for multiple variables with multiple thresholds.

```   
 - _target_: anemoi.models.layers.bounding.NormalizedReluBounding
      variables:
        - ssrd
        - strd
        - avg_tos
      min_val: [0, 0, 271.15]
      normalizer: ['mean-std', 'mean-std', 'mean-std']
```

### Describe the solution you'd like

The current formulation's positive aspect is that the input array's indexing occurs just once, and all the variables are handled together.

From a config viewpoint, it would be cleaner to 

1. call the function multiple times for each min_val.
2. the normalizer for each variable can be read directly from the normalization config and not repeated here.

### Organisation

ECMWF
